//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class radnici
    {
        public radnici()
        {
            this.tim = new HashSet<tim>();
        }
    
        public int idradnik { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string telefon { get; set; }
    
        public virtual ICollection<tim> tim { get; set; }
    }
}
