//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class radna_skupina
    {
        public int id_radnaSkupina { get; set; }
        public int vozilaid_vozilo { get; set; }
        public int posaoid_posao { get; set; }
    
        public virtual posao posao { get; set; }
        public virtual vozila vozila { get; set; }
    }
}
