//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijent
    {
        public klijent()
        {
            this.posao = new HashSet<posao>();
        }
    
        public int id_klijent { get; set; }
        public string adresa { get; set; }
        public string kontakt { get; set; }
        public string naziv { get; set; }
        public string email { get; set; }
        public int posaoid_posao { get; set; }
        public int posaoid_posao2 { get; set; }
        public string primanjeObavijesti { get; set; }
    
        public virtual ICollection<posao> posao { get; set; }
    }
}
