//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class posao
    {
        public posao()
        {
            this.radna_skupina = new HashSet<radna_skupina>();
            this.tim = new HashSet<tim>();
            this.usluga_posao = new HashSet<usluga_posao>();
        }
    
        public int id_posao { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string vrijeme { get; set; }
        public string adresa_ciscenja { get; set; }
        public Nullable<int> velicina_prostora { get; set; }
        public string tip_posla { get; set; }
        public string cijena { get; set; }
        public string vrijeme_izdavanja_racuna { get; set; }
        public int klijent_id { get; set; }
        public int klijentid_klijent { get; set; }
    
        public virtual klijent klijent { get; set; }
        public virtual ICollection<radna_skupina> radna_skupina { get; set; }
        public virtual ICollection<tim> tim { get; set; }
        public virtual ICollection<usluga_posao> usluga_posao { get; set; }
    }
}
