//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServisCiscenjeDBEntities : DbContext
    {
        public ServisCiscenjeDBEntities()
            : base("name=ServisCiscenjeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<klijent> klijent { get; set; }
        public virtual DbSet<korisnici> korisnici { get; set; }
        public virtual DbSet<posao> posao { get; set; }
        public virtual DbSet<radna_skupina> radna_skupina { get; set; }
        public virtual DbSet<radnici> radnici { get; set; }
        public virtual DbSet<tim> tim { get; set; }
        public virtual DbSet<usluga> usluga { get; set; }
        public virtual DbSet<usluga_posao> usluga_posao { get; set; }
        public virtual DbSet<vozila> vozila { get; set; }
    }
}
