//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class usluga
    {
        public usluga()
        {
            this.usluga_posao = new HashSet<usluga_posao>();
        }
    
        public int id_usluga { get; set; }
        public string naziv { get; set; }
        public Nullable<double> cijenaKvadrat { get; set; }
    
        public virtual ICollection<usluga_posao> usluga_posao { get; set; }
    }
}
