//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servis_za_ciscenje.SlojPodataka
{
    using System;
    using System.Collections.Generic;
    
    public partial class vozila
    {
        public vozila()
        {
            this.radna_skupina = new HashSet<radna_skupina>();
        }
    
        public int id_vozilo { get; set; }
        public string registracijska_oznaka { get; set; }
        public string model { get; set; }
    
        public virtual ICollection<radna_skupina> radna_skupina { get; set; }
    }
}
